PYTHON = python

preproc:
	$(PYTHON) 02-python_filtering.py
	$(PYTHON) 03-run_extract_events.py
	$(PYTHON) 04-run_ica.py
	$(PYTHON) 05-make_epochs.py
	$(PYTHON) 06-make_evoked.py
	$(PYTHON) 07-time_frequency.py
	$(PYTHON) 08-make_watershed.py
	$(PYTHON) 09-make_forward.py
	$(PYTHON) 10-make_inverse.py